### ISSUE TITLE
feed/comment interpretation

### ISSUE THREAD

**Issue by darkmorgoth-fl** [fetlife/translations#193]
Is the "Comment" under `en/feed/comment` a noun or a verb? What does it refer to, and why is it capitalised?

**Comment by darkmorgoth-fl** [comment]
Same question for `en/feed/love`

**Comment by rakvat** [comment]
@darkmorgoth-fl thank you for asking!

Both "Comment" and "Love" are verbs in the imperative form. They are used in the beta version of the activity feed that is available to supporters.

**Comment by darkmorgoth-fl** [comment]
Thanks!
