### ISSUE TITLE
en/feed/comments_count in Polish

### ISSUE THREAD

**Issue by darkmorgoth-fl** [fetlife/translations#194]
Hi,

Polish uses 3 different declensions depending on the number preceding the noun. It depends whether the number is 1, ends in 2, 3 or 4, or none of the two.

Can you advise whether you want to change the rules so that I can put the proper declension in the yml, or should I work around it by using something analogous to `comments: %{count_with_delimiter}`?

More info: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html
NPM module tackling this exact issue: https://www.npmjs.com/package/polish-plurals

**Comment by reneklacan** [comment]
@darkmorgoth-fl Hi, general way of solving this is using `one`,`few`,`other` like I did for Slovak translations https://github.com/fetlife/translations/blob/master/locales/sk.yml#L28-L31

But that said not all translations are currently ready to handle languages with more complex grammar rules (like declensions in some languages). But in the future we definitely plan to address this.

**Comment by darkmorgoth-fl** [comment]
Actually, I didn't properly specify how it is in Polish - I forgot that numbers 10-19 are actually using the same form as "other".

@reneklacan how is it in Slovak exactly? Would it be "22 komentárov" or "22 komentáre"? I mean, what numbers is "few" used for? For it to work in Polish, "few" would have to mean "2, 3, 4, xxxyz" where x is 0-9, y is 2-9 and z is 2-4. I think. Then again, "101" would need to use the "one" form. I never actually thought Polish was that complicated ;-)

**Comment by darkmorgoth-fl** [comment]
Nvmd, I found the answer on that gettext manual - Slovak and Czech actually use a different rule than Polish :-(
