### ISSUE TITLE
[Git ACL] Cannot push branch to origin

### ISSUE THREAD

**Issue by ElDomJuan** [fetlife/translations#223]
Hello all.
I've reviewed Portuguese translation but I'm getting the error "remote: Permission to fetlife/translations.git denied to ElDomJuan" after doing "git push origin pt-revision". I've also tried with SSH, having the same problem.
It's first time I use github but I've used gitlab and bitbucket in the past. Should this be done by other way? The steps were the following:

$ git clone git@github.com:fetlife/translations.git .
$ git checkout -b pt-revision
Switched to a new branch 'pt-revision'
$ gedit locales/pt.yml
$ git add locales/pt.yml
$ git commit -s -m "Reviewed Portuguese translation based on en.yml and de.yml files"
[pt-revision 872fcdb] Reviewed Portuguese translation based on en.yml and de.yml files
 1 file changed, 809 insertions(+), 809 deletions(-)
 rewrite locales/pt.yml (70%)
$ git push origin pt-revision
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
ERROR: Permission to fetlife/translations.git denied to ElDomJuan.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git remote -v
origin	git@github.com:fetlife/translations.git (fetch)
origin	git@github.com:fetlife/translations.git (push)

Similar output was presented by doing git clone HTTPS

**Comment by rakvat** [comment]
Hi @ElDomJuan. Thank you for wanting to help. You need to create a fork first: https://guides.github.com/activities/forking/.
