### ISSUE TITLE
Gimme work!

### ISSUE THREAD

**Issue by minusLik** [fetlife/translations#263]
Although there is much activity behind the scenes for sure, I'm starting to wonder when we will be able to continue with our translations because some things are not finished yet. What bugs me most in this regard is the 2FA login page (where we enter our OTP) where only the big red button's label would need to be translated, the rest is done.

Plus, I'd love to continue with the activity stream (aka Home) because it's THE most visible place where you start after logging in and where you land after switching languages. It's strange that after changing the language apparently almost nothing happens until you open the main menu again and I'm afraid people get so accustomed to the English activity stream that they don't bother switching at all anymore.

What do you think?

**Comment by nielsenramon** [comment]
@minusLik I totally get your frustration, it's also something I really wish to tackle! However, we're currently not focussing on it and won't be until we ported our remaining non-responsive pages I'm afraid :-/

**Comment by minusLik** [comment]
@nielsenramon Wouldn't be such a redesign a good opportunity to incorporate multi-language support? The system is already there after all and if I understand it correctly to use it is not much more than to take every string, replace it with a placeholder and put both of them into the language files. Doesn't sound like much work to me, especially when compared to the hassle of finding and replacing all strings on the pages afterwards.
