### ISSUE TITLE
[EN] en.yml a little confusion

### ISSUE THREAD

**Issue by bohoejer** [fetlife/translations#74]
I think line  332 following: Following is wrong. Maybe it should have been  following: Your friends

**Comment by joaocunha** [comment]
@johnbaku what say you? https://github.com/fetlife/translations/blob/master/locales/en.yml#L332

**Comment by rakvat** [comment]
I agree that it's confusing because it links to `https://fetlife.com/explore/following/#/`, which is "Your Friends"

**Comment by joaocunha** [comment]
Makes sense. Merging it in!

**Comment by johnbaku** [comment]
Yeah, it's confusing, but when and if we launch the new feed that will be fixed.
